version: '3.7'
services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret  # Change this password!
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    volumes:
      - ./snmp-exporter:/etc/snmp_exporter:rw
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    ports:
      - '9116:9116'
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring: